In [2]:
import pandas as pd
import numpy as np
import json
import re

In [ ]:
df = pd.read_csv("D:\My_Projects\super_dirty_students.csv")
print(df.head(10))
print(df.info())
print(df.isnull().sum())

   student_id                name       age  gender   score  \
0           1      Claudia Short        20      NaN     NaN
1           2                 NaN       20   Female  ninety
2           3      Kathryn Moyer        20      NaN  ninety
3           4        Ruben Wilson    twenty   fmale      81
4           5       Robert Pruitt        20  Female     NaN
5           6      David Martinez        20    Male  ninety
6           7                 NaN  18 years  FEMALE      71
7           8     Nicholas Dennis        21  FEMALE  ninety
8           9                 NaN    twenty   fmale      77
9          10  Elizabeth Villegas        22  femlae     NaN

                    phone               city                     email  \
0     +1-619-379-4152x102          Katieland          someonegmail.com
1                     NaN          Dawnburgh         psmith@chen.com
2                     NaN   Lake Stevenmouth                       NaN
3                     NaN    Port Pamelafort                   special
4  001-182-659-5631x02803          Kingburgh                       six
5    001-074-828-6016x937        Hugheshaven   nathangibbs@hotmail.com
6       314.018.0928x3134          Sharpfurt      nguyenlisa@@horn.org
7              8091556011        Matthewfort                     avoid
8            854-964-5423  South Paulchester     stacysmith@taylor.biz
9      (205)467-4476x0583    South Dianatown  anthonywalker@@gmail.com

          date_of_join        course attendance    status              gpa  \
0           1662247364  Data Science        NaN    active             3.72
1           2017/08/29  Data Science        NaN    active             1.88
2           2017-08-14  DATA SCIENCE        NaN   pending              NaN
3           1973-09-17   data-sciens        NaN  inactive                0
4           2023/11/25  data_sciense        NaN   pending             4.37
5           1603493647  DATA SCIENCE        110   pending             15.5
6           1982-01-16  data science        NaN    active                0
7           2000.06.26        python         63    active  four point five
8           2000-03-15            ds       110%    active             15.5
9  2013-02-11T07:12:29  data_sciense         99  inactive              3,7

         remarks money_spent           event_time  \
0           good        $135           1629312830
1      excellent        $152  11/10/2001 04:19 AM
2    excellent         185.0           1657837622
3           good     175 USD           1682795130
4        average        $282           2013-10-13
5        average       85,00  1983-04-30T01:46:36
6      excellent       275.0  19/11/2004 11:42 PM
7      excellent         135           1978/09/23
8    excellent       104 USD           1995-10-20
9        average      215,00  2014-12-16T06:44:51

                                         address_raw  \
0  Apartment 37, South Kevin district, Tashkent, ...
1                  UZ 100332 Tashkent South Patricia
2                  Wendyshire 12-kv, dom 1, Tashkent
3  Apartment 16, North Tamara district, Tashkent,...
4                             BROKEN,ADDRESS,DATA,,,
5  Apartment 42, North Jamesfurt district, Tashke...
6             Lake Tracishire 29-kv, dom 8, Tashkent
7           70576 Butler Harbor Suite 847, Janetberg
8             Williamsborough 2-kv, dom 18, Tashkent
9                             BROKEN,ADDRESS,DATA,,,

                                        profile_json
0  {'hobbies': ['gun', 'nice'], 'skills': {'tech'...
1                      {hobbies:['against', 'good']}
2  {'hobbies': ['fast', 'clearly'], 'skills': {'t...
3  {'hobbies': ['left', 'role'], 'skills': {'tech...
4  {'hobbies': ['sort', 'science'], 'skills': {'t...
5                        {hobbies:['order', 'keep']}
6  {'hobbies': ['fall', 'teacher'], 'skills': {'t...
7                                  INVALID_JSON_DATA
8  {'hobbies': ['require', 'open'], 'skills': {'t...
9  {'hobbies': ['management', 'to'], 'skills': {'...
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    1000 non-null   int64
 1   name          665 non-null    str
 2   age           892 non-null    str
 3   gender        781 non-null    str
 4   score         754 non-null    str
 5   phone         629 non-null    str
 6   city          1000 non-null   str
 7   email         849 non-null    str
 8   date_of_join  1000 non-null   str
 9   course        1000 non-null   str
 10  attendance    674 non-null    str
 11  status        1000 non-null   str
 12  gpa           859 non-null    str
 13  remarks       796 non-null    str
 14  money_spent   1000 non-null   str
 15  event_time    1000 non-null   str
 16  address_raw   1000 non-null   str
 17  profile_json  1000 non-null   str
dtypes: int64(1), str(17)
memory usage: 140.8 KB
None
student_id        0
name            335
age             108
gender          219
score           246
phone           371
city              0
email           151
date_of_join      0
course            0
attendance      326
status            0
gpa             141
remarks         204
money_spent       0
event_time        0
address_raw       0
profile_json      0
dtype: int64

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\user\AppData\Local\Temp\ipykernel_16764\2635477649.py:1: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_csv("D:\My_Projects\super_dirty_students.csv")

In [5]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,ninety,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,1603493647,DATA SCIENCE,110,pending,15.5,average,"85,00",1983-04-30T01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18 years,FEMALE,71,314.018.0928x3134,Sharpfurt,nguyenlisa@@horn.org,1982-01-16,data science,NaN,active,0,excellent,275.0,19/11/2004 11:42 PM,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,ninety,8091556011,Matthewfort,avoid,2000.06.26,python,63,active,four point five,excellent,135,1978/09/23,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,twenty,fmale,77,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15,ds,110%,active,15.5,excellent,104 USD,1995-10-20,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,(205)467-4476x0583,South Dianatown,anthonywalker@@gmail.com,2013-02-11T07:12:29,data_sciense,99,inactive,"3,7",average,"215,00",2014-12-16T06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."

In [9]:
# 1. Ham 'object' (aralash), ham 'string' turidagi ustunlarni aniq ko'rsatib tanlaymiz
string_cols = df.select_dtypes(include=['object', 'string']).columns

for col in string_cols:
    # 2. Avval ma'lumotni string ko'rinishiga keltiramiz
    df[col] = df[col].astype(str)
    
    # 3. Bo'sh joylarni olib tashlaymiz
    df[col] = df[col].str.strip()
    
    # 4. Keraksiz so'zlarni haqiqiy bo'sh qiymat (NaN) ga aylantiramiz
    # Bu yerda case=False qilsak, 'none', 'NONE' kabi variantlarni ham ushlaydi
    df[col] = df[col].replace(['nan', 'None', 'NULL', '', 'None', 'nan'], np.nan)

# Tekshirish uchun
print("String ustunlar tozalandi!")

String ustunlar tozalandi!

In [10]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,90.0,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,1603493647,DATA SCIENCE,110,pending,15.5,average,"85,00",1983-04-30T01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18 years,FEMALE,71.0,314.018.0928x3134,Sharpfurt,nguyenlisa@@horn.org,1982-01-16,data science,NaN,active,0,excellent,275.0,19/11/2004 11:42 PM,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,90.0,8091556011,Matthewfort,avoid,2000.06.26,python,63,active,four point five,excellent,135,1978/09/23,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,twenty,fmale,77.0,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15,ds,110%,active,15.5,excellent,104 USD,1995-10-20,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,(205)467-4476x0583,South Dianatown,anthonywalker@@gmail.com,2013-02-11T07:12:29,data_sciense,99,inactive,"3,7",average,"215,00",2014-12-16T06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."

In [13]:
import ast
import pandas as pd
import numpy as np
import re

word_to_num = {
    'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 
    'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10,
    'twenty': 20, 'thirty': 30, 'forty': 40, 'fifty': 50, 'sixty': 60,
    'seventy': 70, 'eighty': 80, 'ninety': 90, 'point': '.'
}

def robust_numeric(val):
    if pd.isna(val) or val == 'nan': return np.nan
    val = str(val).lower().strip().replace(',', '.')
    
    # 1. Regex orqali raqamni qidirish
    match = re.search(r'[-+]?\d*\.?\d+', val)
    if match: return float(match.group())
    
    # 2. So'z bilan yozilgan bo'lsa
    words = re.findall(r'[a-z]+', val)
    num_str = ""
    for w in words:
        if w in word_to_num: num_str += str(word_to_num[w])
    try:
        return float(num_str) if num_str else np.nan
    except: return np.nan

# --- Raqamlarni tozalash ---
df['age'] = df['age'].apply(robust_numeric)
df['score'] = df['score'].apply(robust_numeric)
df['gpa'] = df['gpa'].apply(robust_numeric)
df['attendance'] = df['attendance'].apply(robust_numeric)
df['money_spent'] = df['money_spent'].astype(str).str.replace(',', '.').apply(lambda x: re.sub(r'[^0-9.]', '', x)).replace('', np.nan).astype(float)

# --- Sanalarni tozalash (Warninglarsiz) ---
def clean_date_column(series):
    # Agar qiymat Unix timestamp bo'lsa (uzun raqam)
    def parse_single_date(x):
        if pd.isna(x): return pd.NaT
        try:
            # Agar bu 10 xonali raqam bo'lsa (timestamp)
            if str(x).isdigit() and len(str(x)) >= 10:
                return pd.to_datetime(int(x), unit='s')
        except:
            pass
        # Boshqa hollarda formatni avtomatik aniqlash (mixed formatlar uchun)
        return pd.to_datetime(x, errors='coerce', dayfirst=False)

    return series.apply(parse_single_date)

df['date_of_join'] = clean_date_column(df['date_of_join'])
df['event_time'] = clean_date_column(df['event_time'])

print("Step 3: Raqam va sanalar muvaffaqiyatli tozalandi (Warninglarsiz)!")

Step 3: Raqam va sanalar muvaffaqiyatli tozalandi (Warninglarsiz)!

In [14]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20.0,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,NaT,Data Science,NaN,active,3.72,good,135.0,NaT,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20.0,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20.0,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,NaT,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20.0,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,NaT,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20.0,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20.0,Male,90.0,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,NaT,DATA SCIENCE,110.0,pending,15.50,average,85.0,1983-04-30 01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18.0,FEMALE,71.0,314.018.0928x3134,Sharpfurt,nguyenlisa@@horn.org,1982-01-16 00:00:00,data science,NaN,active,0.00,excellent,275.0,2004-11-19 23:42:00,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21.0,FEMALE,90.0,8091556011,Matthewfort,avoid,2000-06-26 00:00:00,python,63.0,active,4.50,excellent,135.0,1978-09-23 00:00:00,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,20.0,fmale,77.0,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,110.0,active,15.50,excellent,104.0,1995-10-20 00:00:00,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22.0,femlae,NaN,(205)467-4476x0583,South Dianatown,anthonywalker@@gmail.com,2013-02-11 07:12:29,data_sciense,99.0,inactive,3.70,average,215.0,2014-12-16 06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."

In [15]:
def clean_email(email):
    if pd.isna(email) or '@' not in str(email): return np.nan
    email = str(email).lower().strip()
    return email if email.count('@') == 1 else np.nan

df['email'] = df['email'].apply(clean_email)

def clean_phone(phone):
    if pd.isna(phone): return np.nan
    nums = re.sub(r'\D', '', str(phone)) # Faqat raqamlarni qoldirish
    if len(nums) >= 9:
        return "+998" + nums[-9:] # Oxirgi 9 ta raqamni olib standartlash
    return np.nan

df['phone'] = df['phone'].apply(clean_phone)

In [16]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20.0,NaN,NaN,+998794152102,Katieland,NaN,NaT,Data Science,NaN,active,3.72,good,135.0,NaT,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20.0,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20.0,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,NaT,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20.0,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,NaT,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20.0,Female,NaN,+998563102803,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20.0,Male,90.0,+998286016937,Hugheshaven,nathangibbs@hotmail.com,NaT,DATA SCIENCE,110.0,pending,15.50,average,85.0,1983-04-30 01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18.0,FEMALE,71.0,+998809283134,Sharpfurt,NaN,1982-01-16 00:00:00,data science,NaN,active,0.00,excellent,275.0,2004-11-19 23:42:00,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21.0,FEMALE,90.0,+998091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,63.0,active,4.50,excellent,135.0,1978-09-23 00:00:00,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,20.0,fmale,77.0,+998549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,110.0,active,15.50,excellent,104.0,1995-10-20 00:00:00,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22.0,femlae,NaN,+998744760583,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,99.0,inactive,3.70,average,215.0,2014-12-16 06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."

In [17]:
def parse_profile(json_str):
    if pd.isna(json_str) or json_str == 'INVALID_JSON_DATA': return {}
    try:
        # Ba'zan JSON bir tirnoqli bo'ladi, ast.literal_eval shuni o'qiydi
        return ast.literal_eval(json_str)
    except:
        return {}

profile_data = pd.json_normalize(df['profile_json'].apply(parse_profile))
# Asosiy df bilan birlashtirish
df = pd.concat([df.reset_index(drop=True), profile_data.reset_index(drop=True)], axis=1)

In [18]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,profile_json,hobbies,devices,skills.tech.python,skills.tech.excel,skills.tech.sql,skills.soft,family.siblings,family.income.father,family.income.mother
0,1,Claudia Short,20.0,NaN,NaN,+998794152102,Katieland,NaN,NaT,Data Science,...,"{'hobbies': ['gun', 'nice'], 'skills': {'tech'...","[gun, nice]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",2.0,5.0,1.0,"[with, onto]",4.0,1198.0,1089.0
1,2,NaN,20.0,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,"{hobbies:['against', 'good']}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20.0,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,"{'hobbies': ['fast', 'clearly'], 'skills': {'t...","[fast, clearly]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",5.0,3.0,1.0,"[despite, clearly]",1.0,263.0,202.0
3,4,Ruben Wilson,20.0,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,"{'hobbies': ['left', 'role'], 'skills': {'tech...","[left, role]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",3.0,5.0,1.0,"[full, series]",4.0,508.0,698.0
4,5,Robert Pruitt,20.0,Female,NaN,+998563102803,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,"{'hobbies': ['sort', 'science'], 'skills': {'t...","[sort, science]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",1.0,4.0,1.0,"[whose, save]",3.0,862.0,1058.0
5,6,David Martinez,20.0,Male,90.0,+998286016937,Hugheshaven,nathangibbs@hotmail.com,NaT,DATA SCIENCE,...,"{hobbies:['order', 'keep']}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,18.0,FEMALE,71.0,+998809283134,Sharpfurt,NaN,1982-01-16 00:00:00,data science,...,"{'hobbies': ['fall', 'teacher'], 'skills': {'t...","[fall, teacher]","[{'type': 'laptop', 'brand': 'HP', 'year': 201...",4.0,1.0,4.0,"[teacher, good]",3.0,1270.0,931.0
7,8,Nicholas Dennis,21.0,FEMALE,90.0,+998091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,...,INVALID_JSON_DATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,NaN,20.0,fmale,77.0,+998549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,...,"{'hobbies': ['require', 'open'], 'skills': {'t...","[require, open]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",1.0,5.0,4.0,"[partner, walk]",0.0,850.0,1062.0
9,10,Elizabeth Villegas,22.0,femlae,NaN,+998744760583,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,...,"{'hobbies': ['management', 'to'], 'skills': {'...","[management, to]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",1.0,1.0,4.0,"[beat, southern]",3.0,597.0,1150.0

In [19]:
def parse_address(addr):
    if pd.isna(addr) or "BROKEN" in str(addr): 
        return pd.Series([None, None, None])
    
    city = 'Tashkent' if 'Tashkent' in str(addr) else 'Other'
    zip_code = re.findall(r'\d{6}', str(addr))
    dist_match = re.search(r'([^,]+)\sdistrict', str(addr))
    
    return pd.Series([
        city, 
        dist_match.group(1).strip() if dist_match else None, 
        zip_code[0] if zip_code else None
    ])

df[['addr_city', 'addr_district', 'addr_postal']] = df['address_raw'].apply(parse_address)

In [20]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,skills.tech.python,skills.tech.excel,skills.tech.sql,skills.soft,family.siblings,family.income.father,family.income.mother,addr_city,addr_district,addr_postal
0,1,Claudia Short,20.0,NaN,NaN,+998794152102,Katieland,NaN,NaT,Data Science,...,2.0,5.0,1.0,"[with, onto]",4.0,1198.0,1089.0,Tashkent,South Kevin,100539
1,2,NaN,20.0,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,NaN,100332
2,3,Kathryn Moyer,20.0,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,5.0,3.0,1.0,"[despite, clearly]",1.0,263.0,202.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,20.0,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,3.0,5.0,1.0,"[full, series]",4.0,508.0,698.0,Tashkent,North Tamara,100097
4,5,Robert Pruitt,20.0,Female,NaN,+998563102803,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,1.0,4.0,1.0,"[whose, save]",3.0,862.0,1058.0,NaN,NaN,NaN
5,6,David Martinez,20.0,Male,90.0,+998286016937,Hugheshaven,nathangibbs@hotmail.com,NaT,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,North Jamesfurt,100551
6,7,NaN,18.0,FEMALE,71.0,+998809283134,Sharpfurt,NaN,1982-01-16 00:00:00,data science,...,4.0,1.0,4.0,"[teacher, good]",3.0,1270.0,931.0,Tashkent,NaN,NaN
7,8,Nicholas Dennis,21.0,FEMALE,90.0,+998091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,NaN,NaN
8,9,NaN,20.0,fmale,77.0,+998549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,...,1.0,5.0,4.0,"[partner, walk]",0.0,850.0,1062.0,Tashkent,NaN,NaN
9,10,Elizabeth Villegas,22.0,femlae,NaN,+998744760583,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,...,1.0,1.0,4.0,"[beat, southern]",3.0,597.0,1150.0,NaN,NaN,NaN

In [21]:
# Student_id bo'yicha duplikatlarni olib tashlash
df = df.drop_duplicates(subset=['student_id'], keep='first')
# Muhim bo'shliqlarni tozalash (ixtiyoriy)
# df = df.dropna(subset=['student_id'])

In [22]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,skills.tech.python,skills.tech.excel,skills.tech.sql,skills.soft,family.siblings,family.income.father,family.income.mother,addr_city,addr_district,addr_postal
0,1,Claudia Short,20.0,NaN,NaN,+998794152102,Katieland,NaN,NaT,Data Science,...,2.0,5.0,1.0,"[with, onto]",4.0,1198.0,1089.0,Tashkent,South Kevin,100539
1,2,NaN,20.0,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,NaN,100332
2,3,Kathryn Moyer,20.0,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,5.0,3.0,1.0,"[despite, clearly]",1.0,263.0,202.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,20.0,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,3.0,5.0,1.0,"[full, series]",4.0,508.0,698.0,Tashkent,North Tamara,100097
4,5,Robert Pruitt,20.0,Female,NaN,+998563102803,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,1.0,4.0,1.0,"[whose, save]",3.0,862.0,1058.0,NaN,NaN,NaN
5,6,David Martinez,20.0,Male,90.0,+998286016937,Hugheshaven,nathangibbs@hotmail.com,NaT,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,North Jamesfurt,100551
6,7,NaN,18.0,FEMALE,71.0,+998809283134,Sharpfurt,NaN,1982-01-16 00:00:00,data science,...,4.0,1.0,4.0,"[teacher, good]",3.0,1270.0,931.0,Tashkent,NaN,NaN
7,8,Nicholas Dennis,21.0,FEMALE,90.0,+998091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,NaN,NaN
8,9,NaN,20.0,fmale,77.0,+998549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,...,1.0,5.0,4.0,"[partner, walk]",0.0,850.0,1062.0,Tashkent,NaN,NaN
9,10,Elizabeth Villegas,22.0,femlae,NaN,+998744760583,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,...,1.0,1.0,4.0,"[beat, southern]",3.0,597.0,1150.0,NaN,NaN,NaN

In [23]:
# Gender normalizatsiya
df['gender'] = df['gender'].astype(str).str.capitalize()
df.loc[df['gender'].str.contains('Fem|Fm', na=False), 'gender'] = 'Female'
df.loc[df['gender'].str.contains('Male|M', na=False) & ~df['gender'].str.contains('Fe', na=False), 'gender'] = 'Male'
df.loc[~df['gender'].isin(['Male', 'Female']), 'gender'] = 'Unknown'

# Course normalizatsiya
def map_course(val):
    val = str(val).lower()
    if 'data' in val or 'ds' in val: return 'Data Science'
    if 'python' in val: return 'Python'
    return 'Other'

df['course'] = df['course'].apply(map_course)

In [24]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,skills.tech.python,skills.tech.excel,skills.tech.sql,skills.soft,family.siblings,family.income.father,family.income.mother,addr_city,addr_district,addr_postal
0,1,Claudia Short,20.0,Unknown,NaN,+998794152102,Katieland,NaN,NaT,Data Science,...,2.0,5.0,1.0,"[with, onto]",4.0,1198.0,1089.0,Tashkent,South Kevin,100539
1,2,NaN,20.0,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,NaN,100332
2,3,Kathryn Moyer,20.0,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data Science,...,5.0,3.0,1.0,"[despite, clearly]",1.0,263.0,202.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,20.0,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data Science,...,3.0,5.0,1.0,"[full, series]",4.0,508.0,698.0,Tashkent,North Tamara,100097
4,5,Robert Pruitt,20.0,Female,NaN,+998563102803,Kingburgh,NaN,2023-11-25 00:00:00,Data Science,...,1.0,4.0,1.0,"[whose, save]",3.0,862.0,1058.0,NaN,NaN,NaN
5,6,David Martinez,20.0,Male,90.0,+998286016937,Hugheshaven,nathangibbs@hotmail.com,NaT,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,North Jamesfurt,100551
6,7,NaN,18.0,Female,71.0,+998809283134,Sharpfurt,NaN,1982-01-16 00:00:00,Data Science,...,4.0,1.0,4.0,"[teacher, good]",3.0,1270.0,931.0,Tashkent,NaN,NaN
7,8,Nicholas Dennis,21.0,Female,90.0,+998091556011,Matthewfort,NaN,2000-06-26 00:00:00,Python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,NaN,NaN
8,9,NaN,20.0,Female,77.0,+998549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,Data Science,...,1.0,5.0,4.0,"[partner, walk]",0.0,850.0,1062.0,Tashkent,NaN,NaN
9,10,Elizabeth Villegas,22.0,Female,NaN,+998744760583,South Dianatown,NaN,2013-02-11 07:12:29,Data Science,...,1.0,1.0,4.0,"[beat, southern]",3.0,597.0,1150.0,NaN,NaN,NaN

In [32]:
df['date_of_join'] = pd.to_datetime(df['date_of_join']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['event_time'] = pd.to_datetime(df['event_time']).dt.strftime('%Y-%m-%d %H:%M:%S')

df.to_csv('super_dirty_students_cleaned.csv', index=False)
print("Fayl 'super_dirty_students_cleaned.csv' nomi bilan saqlandi.")

Fayl 'super_dirty_students_cleaned.csv' nomi bilan saqlandi.

In [26]:
print(f"Tozalangan qatorlar soni: {len(df)}")
print(f"GPA diapazoni: {df['gpa'].min()} - {df['gpa'].max()}")
print(f"Telefon raqami borlar: {df['phone'].notnull().sum()}")

Tozalangan qatorlar soni: 1000
GPA diapazoni: -2.0 - 15.5
Telefon raqami borlar: 629

In [40]:
import pandas as pd

# Faylni o'qish
df = pd.read_csv("D:\My_Projects\Super_dirty_students_project\super_dirty_students_cleaned.csv")

# 1. Umumiy dublikat qatorlar sonini tekshirish
duplicate_count = df.duplicated().sum()
print(f"Jami dublikat qatorlar soni: {duplicate_count}")

# 2. Agar dublikat bo'lsa, ularni ko'rib olish
if duplicate_count > 0:
    duplicates = df[df.duplicated(keep=False)] # keep=False barcha takrorlanganlarini ko'rsatadi
    print("\nDublikat qatorlar namunalari:")
    print(duplicates.head())
else:
    print("Dublikatlar topilmadi!")

Jami dublikat qatorlar soni: 0
Dublikatlar topilmadi!

<>:4: SyntaxWarning: invalid escape sequence '\M'
<>:4: SyntaxWarning: invalid escape sequence '\M'
C:\Users\user\AppData\Local\Temp\ipykernel_16764\631847795.py:4: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_csv("D:\My_Projects\Super_dirty_students_project\super_dirty_students_cleaned.csv")